name: Pages-Repository
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - name: Get config file
        run: |
          default="config/_default/hugo"
          if [[ -f $default.toml ]]; then
            CONF="$default.toml"
          elif [[ -f $default.yaml ]]; then
            CONF="$default.yaml"
          elif [[ -f $default.yml ]]; then
            CONF="$default.yml"
          elif [[ -f config.yml ]]; then
            CONF="config.yml"
          elif [[ -f config.yaml ]]; then
            CONF="config.yaml"
          elif [[ -f config.toml ]]; then
            CONF="config.toml"
          elif [[ -f hugo.toml ]]; then
            CONF="hugo.toml"
          elif [[ -f hugo.yml ]]; then
            CONF="hugo.yml"
          elif [[ -f hugo.yaml ]]; then
            CONF="hugo.yaml"
          fi
          echo "CONF=$CONF" >>$GITHUB_ENV
          echo "current config file is $CONF"

      - name: Get baseURL
        run: |
          baseURL=$(cat ${{ env.CONF }} | awk '/^baseURL/' | awk '{print $3}' | sed "s|[\'\"]||g" | awk -F '//' '{print $2}' | sed "s|/||")
          if [[ $baseURL ]]; then
            echo "CNAME=$baseURL" >>$GITHUB_ENV
            echo "baseURL is $baseURL"
          else
            echo "Check baseURL setting in root ${{ env.CONF }} please."
            cat ${{ env.CONF }}
          fi

      - name: Check ACTION_REPO
        run: |
          ACTION_REPO=$(echo ${{ github.repository }} | awk -F '/' '{print $2}')
          if [[ $ACTION_REPO == '${{ github.actor }}.github.io' ]]; then
            echo "Action in Page repository, do nothing."
            echo "PAGE_REPO=true" >>$GITHUB_ENV
            exit
          else
            sed -i "s|${{ env.CNAME }}|${{ github.actor }}.github.io/$ACTION_REPO|" ${{ env.CONF }}
            cat ${{ env.CONF }}
          fi

      - name: Setup Hugo
        if: ${{ env.PAGE_REPO != 'true' }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'
          extended: true

      - name: Build
        if: ${{ env.PAGE_REPO != 'true' }}
        run: hugo --minify

      - name: Deploy
        if: ${{ env.PAGE_REPO != 'true' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GAYHUB_TOKEN }} # 该项适用于发布到源码相同repo的情况，不能用于发布到其他repo
          personal_token: ${{ secrets.ACTION_ACCESS_TOKEN }}	# 发布到其他repo需要提供上面生成的personal access token
          publish_dir: ./public	# Source Directory，hugo默认生成静态网页到public文件夹
          publish_branch: pages-hugo	# 发布到哪个branch
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true # make your publish branch with only the latest commit